In [ ]:
# processed-seoul-crime과 processed-seoul-cctv를 읽어서 병합
# 상관관계 확인

In [2]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
seoul_cctv = pd.read_csv("data-files/processed-seoul-cctv.csv", encoding="utf-8")
seoul_crime = pd.read_csv("data-files/processed-seoul-crime.csv", encoding="utf-8")

In [6]:
seoul_cctv.info()
seoul_crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   자치구     25 non-null     object
 1   발생합계    25 non-null     float64
 2   검거합계    25 non-null     float64
 3   살인      25 non-null     float64
 4   강도      25 non-null     float64
 5   강간      25 non-null     float64
 6   절도      25 non-null     float64
 7   폭력      25 non-null     float64
 8   살인검거율   25 non-null     float64
 9   강도검거율   25 non-null     float64
 10  강간검거율   25 non-null     float64
 11  절도검거율   25 non-null     float64
 12  폭력검거율   25 non-null     float64
dtypes: float64(12), object(1)
memory usage: 2.7+ KB

In [7]:
seoul_cctv.head()

,자치구,총계,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년,최근증가율
0,종로구,1980,36,540,107,161,131,158,152,69,250,85,291,46.233383
1,중구,2584,130,87,77,236,240,372,386,155,361,403,137,53.535354
2,용산구,2847,44,50,68,83,295,491,115,322,623,422,334,93.937330
3,성동구,4047,58,99,110,366,279,945,459,647,485,367,232,36.584543
4,광진구,3480,507,82,84,64,21,465,443,709,172,662,271,46.526316

In [8]:
seoul_crime.head()

,자치구,발생합계,검거합계,살인,강도,강간,절도,폭력,살인검거율,강도검거율,강간검거율,절도검거율,폭력검거율
0,종로구,0.198787,0.470835,0.454545,0.125000,0.166008,0.191875,0.211924,0.000000,0.692308,1.000000,0.989112,0.446840
1,중구,0.233551,0.250725,0.454545,0.208333,0.175889,0.316875,0.184909,0.500000,0.692308,0.018535,0.510207,0.595719
2,용산구,0.121559,0.117628,0.181818,0.000000,0.136364,0.108125,0.129949,0.166667,0.692308,0.048096,0.226570,0.259137
3,성동구,0.058796,0.069610,0.181818,0.125000,0.075099,0.083125,0.036330,0.833333,0.000000,0.051551,0.386494,0.437118
4,광진구,0.286281,0.292620,0.363636,0.125000,0.268775,0.401250,0.206800,0.100000,0.692308,0.058152,0.317634,0.681971

In [9]:
seoul_cctv_crime = pd.merge(seoul_cctv, seoul_crime, on="자치구")

In [10]:
seoul_cctv_crime.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25 entries, 0 to 24
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   자치구                25 non-null     object
 1   총계                 25 non-null     int64
 2   2013년 이전 설치된 CCTV  25 non-null     int64
 3   2013년              25 non-null     int64
 4   2014년              25 non-null     int64
 5   2015년              25 non-null     int64
 6   2016년              25 non-null     int64
 7   2017년              25 non-null     int64
 8   2018년              25 non-null     int64
 9   2019년              25 non-null     int64
 10  2020년              25 non-null     int64
 11  2021년              25 non-null     int64
 12  2022년              25 non-null     int64
 13  최근증가율              25 non-null     float64
 14  발생합계               25 non-null     float64
 15  검거합계               25 non-null     float64
 16  살인                 25 non-null     float64
 17  강도                 25 non-null     float64
 18  강간                 25 non-null     float64
 19  절도                 25 non-null     float64
 20  폭력                 25 non-null     float64
 21  살인검거율              25 non-null     float64
 22  강도검거율              25 non-null     float64
 23  강간검거율              25 non-null     float64
 24  절도검거율              25 non-null     float64
 25  폭력검거율              25 non-null     float64
dtypes: float64(13), int64(12), object(1)
memory usage: 5.3+ KB

In [11]:
seoul_cctv_crime.head()

,자치구,총계,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,...,살인,강도,강간,절도,폭력,살인검거율,강도검거율,강간검거율,절도검거율,폭력검거율
0,종로구,1980,36,540,107,161,131,158,152,69,...,0.454545,0.125000,0.166008,0.191875,0.211924,0.000000,0.692308,1.000000,0.989112,0.446840
1,중구,2584,130,87,77,236,240,372,386,155,...,0.454545,0.208333,0.175889,0.316875,0.184909,0.500000,0.692308,0.018535,0.510207,0.595719
2,용산구,2847,44,50,68,83,295,491,115,322,...,0.181818,0.000000,0.136364,0.108125,0.129949,0.166667,0.692308,0.048096,0.226570,0.259137
3,성동구,4047,58,99,110,366,279,945,459,647,...,0.181818,0.125000,0.075099,0.083125,0.036330,0.833333,0.000000,0.051551,0.386494,0.437118
4,광진구,3480,507,82,84,64,21,465,443,709,...,0.363636,0.125000,0.268775,0.401250,0.206800,0.100000,0.692308,0.058152,0.317634,0.681971

In [14]:
minv = seoul_cctv_crime["총계"].min()
maxv = seoul_cctv_crime["총계"].max()
minv, maxv
# seoul_cctv_crime["총계"] = ( seoul_cctv_crime["총계"] - minv ) / (maxv - minv)

(1980, 7243)

In [22]:
agg_result = seoul_cctv_crime["총계"].agg([max, min]) # aggregate
# print( type(agg_result) )
# agg_result
seoul_cctv_crime["총계"] = \
    ( seoul_cctv_crime["총계"] - agg_result['min'] ) / (agg_result['max'] - agg_result['min'])

In [23]:
seoul_cctv_crime["총계"].agg([np.min, np.max])

amin    0.0
amax    1.0
Name: 총계, dtype: float64

In [25]:
seoul_cctv_crime[["총계", "살인", "강도", "강간", "절도", "폭력"]].corr(method="pearson")

          총계        살인        강도        강간        절도        폭력
총계  1.000000  0.533954  0.635825  0.644839  0.569906  0.633743
살인  0.533954  1.000000  0.631066  0.753431  0.562919  0.677930
강도  0.635825  0.631066  1.000000  0.814157  0.760986  0.781869
강간  0.644839  0.753431  0.814157  1.000000  0.815416  0.848741
절도  0.569906  0.562919  0.760986  0.815416  1.000000  0.931505
폭력  0.633743  0.677930  0.781869  0.848741  0.931505  1.000000

In [26]:
seoul_cctv_crime[["총계", "살인검거율", "강도검거율", "강간검거율", "절도검거율", "폭력검거율"]].corr(method="pearson")

             총계     살인검거율     강도검거율     강간검거율     절도검거율     폭력검거율
총계     1.000000 -0.030158 -0.149814 -0.292082 -0.283549  0.149313
살인검거율 -0.030158  1.000000 -0.188641 -0.405230  0.031737 -0.228198
강도검거율 -0.149814 -0.188641  1.000000  0.061169  0.098838  0.158042
강간검거율 -0.292082 -0.405230  0.061169  1.000000  0.491008  0.043821
절도검거율 -0.283549  0.031737  0.098838  0.491008  1.000000  0.477193
폭력검거율  0.149313 -0.228198  0.158042  0.043821  0.477193  1.000000